### ISSUE TITLE
Create a machine-readable output flag

### ISSUE THREAD

**Issue by Grace-H** [Grace-H/antcode#1]
## Description
Add a flag that will switch the output from human-readable to something that is easier for another program to read & parse.

## Tasks
- [ ] Add commandline args
- [ ] Decide on output format
- [ ] Add new print map function
